definitions:
  api.Response:
    properties:
      data: {}
      error:
        type: string
      success:
        type: boolean
    type: object
  dataapi.NewAgentProfileQuery:
    properties:
      agreeableness:
        type: number
      api_key:
        type: string
      conscientiousness:
        type: number
      extraversion:
        type: number
      neuroticism:
        type: number
      openness:
        type: number
    type: object
info:
  contact:
    email: zhanyunze0601@gmai.com
    name: 1Vewton
    url: https://github.com/1Vewton
  description: A service to simulate emotion for agent
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Emotion Simulator
  version: "1.0"
paths:
  /v1/data/addAgentProfile:
    post:
      consumes:
      - application/json
      description: Adds profile for agent
      parameters:
      - description: Query parameters
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dataapi.NewAgentProfileQuery'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
      summary: Adds profile for agent
      tags:
      - example
  /v1/utils/health:
    get:
      consumes:
      - application/json
      description: check health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
      summary: Checks health
      tags:
      - example
swagger: "2.0"
